name: Build and push website

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  # Cancels jobs running if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_website:
    name: Run doc build
    runs-on: ubuntu-latest
    container:
      # UNDO ME
      # image: firedrakeproject/firedrake-docdeps:latest
      image: firedrakeproject/firedrake-docdeps:piptest
      options: --user root
    env:
      # Since we are running as root we need to set PYTHONPATH to be able to find the installed
      # packages
      PYTHONPATH: /home/firedrake/firedrake:/home/firedrake/.local/lib/python3.12/site-packages
    steps:
      - uses: actions/checkout@v4
        with:
          path: firedrake-repo
          repository: firedrakeproject/firedrake

      - name: Install Firedrake
        run: |
          : # Pass '--system-site-packages' so already installed packages can be found
          python3 -m venv --system-site-packages venv
          . venv/bin/activate
          pip uninstall -y firedrake
          pip install --verbose './firedrake-repo[docs]'

      - name: Check bibtex
        run: |
          . venv/bin/activate
          make -C firedrake-repo/docs validate-bibtex

      - name: Check documentation links
        run: |
          . venv/bin/activate
          make -C firedrake-repo/docs linkcheck

      - name: Build docs
        run: |
          . venv/bin/activate
          cd firedrake-repo/docs
          make html
          make latex
          make latexpdf

      - name: Copy manual to HTML tree
        run: |
          cd firedrake-repo/docs
          cp build/latex/Firedrake.pdf build/html/_static/manual.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: /__w/firedrakeproject.github.io/firedrakeproject.github.io/firedrake-repo/docs/build/html
          retention-days: 1

      - name: Fix repo permissions (needed for keepalive)
        run: git config --global --add safe.directory /__w/firedrakeproject.github.io/firedrakeproject.github.io

      - name: Checkout for keepalive
        uses: actions/checkout@v4

      - name: Keepalive commit
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          time_elapsed: 30

  deploy:
    name: Deploy Github pages
    needs: build_website
    runs-on: ubuntu-latest
    # UNDO ME: force update on PR pass!
    # if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://firedrakeproject.github.io
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
